# Generated by Django 5.0.4 on 2024-04-24 10:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('game', models.CharField(max_length=16)),
                ('players', models.JSONField(default=dict)),
                ('stats', models.JSONField(default=dict)),
                ('score', models.JSONField(default=dict)),
                ('tournament', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('playing', 'Playing'), ('finished', 'Finished')], default='created', max_length=32)),
            ],
            options={
                'verbose_name': 'matches',
            },
        ),
        migrations.CreateModel(
            name='Tournaments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('game', models.CharField(max_length=16)),
                ('size', models.PositiveSmallIntegerField(default=4)),
                ('participants', models.JSONField(default=dict)),
                ('host', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('registration', 'Registration'), ('started', 'Started'), ('finished', 'Finished')], default='registration', max_length=32)),
                ('draw', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'tournaments',
            },
        ),
    ]
