# Generated by Django 5.0.2 on 2024-02-22 19:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournaments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('game', models.CharField(max_length=16)),
                ('size', models.PositiveSmallIntegerField(default=4)),
                ('participants', models.JSONField(default=dict)),
                ('host', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('registration', 'Registration'), ('started', 'Started'), ('finished', 'Finished')], default='registration', max_length=32)),
                ('draw', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'tournaments',
            },
        ),
    ]
