services:
  postgres:
    container_name: postgres
    build: ./postgres
    restart: always
    expose:
      - 5432
    networks:
      - ft_transcendence
    volumes:
      - ./postgres/DB_DATA:/var/lib/postgresql/data
    env_file: .pgenv

  nginx:
    container_name: nginx
    build: ./nginx
    depends_on:
      - auth
      - game
      - chat
      - postgres
      - logstash
    restart: always
    networks:
      - ft_transcendence
    volumes:
      - ./nginx/frontend/:/usr/share/nginx/html
    ports:
      - 443:443
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://localhost:514"
        tag: nginx

  auth:
    container_name: auth
    build: ./backend/auth
    depends_on:
      - postgres
      - logstash
    restart: always
    expose:
      - 8080
    networks:
      - ft_transcendence
    volumes:
      - ./backend/auth:/var/www/auth
    env_file: .doenv
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://localhost:514"
        tag: auth

  game:
    container_name: game
    build: ./backend/game
    depends_on:
      - postgres
      - logstash
    restart: always
    expose:
      - 8081
    networks:
      - ft_transcendence
    volumes:
      - ./backend/game:/var/www/game
    env_file: .doenv
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://localhost:514"
        tag: game

  chat:
    container_name: chat
    build: ./backend/chat
    depends_on:
      - postgres
      - logstash
    restart: always
    expose:
      - 8082
    networks:
      - ft_transcendence
    volumes:
      - ./backend/chat:/var/www/chat
    env_file: .doenv
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://localhost:514"
        tag: chat

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alert.rules.yml:/etc/prometheus/alert.rules.yml
    ports:
      - 9090:9090
    networks:
      - ft_transcendence
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=15d'

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
    - 8080:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - ft_transcendence

  nginx-exporter:
    container_name: nginx-exporter
    image: nginx/nginx-prometheus-exporter
    command: "--nginx.scrape-uri=https://nginx/stub_status"
    ports:
      - 9113:9113
    networks:
      - ft_transcendence

  postgres-exporter:
    container_name: postgres-exporter
    image: bitnami/postgres-exporter
    ports:
      - 9187:9187
    networks:
      - ft_transcendence
    env_file: .doenv

  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    networks:
      - ft_transcendence
    env_file: .doenv

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    environment:
      discovery.type: single-node
      xpack.security.transport.ssl.enabled: "false"
      xpack.security.enrollment.enabled: "true"
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    ports:
      - 9200:9200
    volumes:
      - ./elasticsearch/esdata:/usr/share/elasticsearch/data
    env_file: .doenv

  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:8.13.4
    ports:
      - 514:514
    volumes:
      - ./logstash/config:/usr/share/logstash/config
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    depends_on:
      - elasticsearch

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.13.4
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    env_file: .doenv

networks:
  ft_transcendence:
    driver: bridge
