global:
  scrape_interval: 15s

scrape_configs:
  - job_name: postgres-exporter
    static_configs:
      - targets: ['postgres-exporter:9187']
  - job_name: nginx-exporter
    static_configs:
      - targets: ['nginx-exporter:9113']
  - job_name: cadvisor
    static_configs:
      - targets: ['cadvisor:8080']
