# Generated by Django 5.0.2 on 2024-02-29 14:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=32, unique=True)),
                ('email', models.EmailField(max_length=255)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('in-game', 'In-game')], default='offline', max_length=16)),
                ('avatar_path', models.ImageField(default='avatars/default/default_avatar.jpg', upload_to='avatars')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('two_factor_enabled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Users',
            },
        ),
        migrations.CreateModel(
            name='QRMeta',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('secret', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': 'QRMeta',
            },
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('request', 'Request'), ('accept', 'Accept'), ('reject', 'Reject'), ('removed', 'Removed')], default='request', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_friends', to=settings.AUTH_USER_MODEL, to_field='login')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_friends', to=settings.AUTH_USER_MODEL, to_field='login')),
            ],
            options={
                'verbose_name': 'Friends',
                'unique_together': {('user', 'friend')},
            },
        ),
    ]
