# Generated by Django 5.0.4 on 2024-05-13 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_rooms_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='sender',
            field=models.CharField(max_length=64),
        ),
    ]
